HySound/ViewModels/Main/LibraryViewModel.cs
using HySound.Models.Models;
using HySound.ViewModels.Album;
using HySound.ViewModels.Playlist;

namespace HySound.ViewModels.Main
{
    public class LibraryViewModel
    {
        public List<TrackViewModel> Tracks { get; set; }
        public List<AlbumViewModel> Albums { get; set; }
        public List<PlaylistViewModel> Playlists { get; set; }
    }
}

HySound/ViewModels/Main/SearchViewModel.cs
using HySound.ViewModels.Album;
using HySound.ViewModels.Playlist;
using HySound.ViewModels.User;

namespace HySound.ViewModels.Main
{
    public class SearchViewModel
    {
        public string? SearchFilter { get; set; }
        public string? filter { get; set; }

        public List<TrackViewModel>? Tracks { get; set; }
        public List<AlbumViewModel>? Albums { get; set; }
        public List<PlaylistViewModel>? Playlists { get; set; }
        public List<UserViewModel>? User { get; set; }
    }
}

HySound/Controllers/AlbumController.cs
using HySound.Core.Service;
using HySound.Core.Service.IService;
using HySound.Models;
using HySound.ViewModels.Album;
using HySound.Models.Models;
using HySound.ViewModels.Track;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HySound.ViewModels;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Mvc.ApplicationModels;
using Microsoft.AspNetCore.Identity;

namespace HySound.Controllers
{
    public class AlbumController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        IAlbumService albumService;
        IUserService userService;
        ITrackService trackService;
        ILikeService likeService;

        private readonly Cloudinary _cloudinary;
        private readonly IConfiguration _configuration;
        CloudinaryService cloudService;
        public AlbumController(ILikeService _likeService,UserManager<IdentityUser> _userManager, IConfiguration configuration, CloudinaryService cloud, ITrackService _trackService, IAlbumService _albumService, IUserService userService)
        {
            albumService = _albumService;
            this.userService = userService;
            trackService = _trackService;
            likeService = _likeService;
            userManager = _userManager;

            this.cloudService = cloud;

            _configuration = configuration;
            var account = new Account(
           _configuration["Cloudinary:CloudName"],
           _configuration["Cloudinary:ApiKey"],
           _configuration["Cloudinary:ApiSecret"]
       );
            _cloudinary = new Cloudinary(account);
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> AlbumDetails(int id)
        {
            var tempUser = await userManager.FindByEmailAsync(User.Identity.Name);
            User user = await userService.GetUserAsync(x => x.Email == tempUser.Email);

            bool isLiked = false;

            var like = likeService.GetAll().Where(x => x.UserId == user.Id && x.AlbumId == id);
            if (like.Any())
            {
                isLiked = true;
            }

            var album = await albumService.GetAll().Where(x=>x.Id==id).Include(x=>x.User).Include(x=>x.Tracks)
                .Select(x=> new AlbumViewModel
                {
                    CoverImage = x.CoverImage,
                    Id = id,
                    Title=x.Title,
                    UserName=x.User.Username,
                    Tracks = x.Tracks.ToList(),
                    IsLiked=isLiked
                }).FirstOrDefaultAsync();


            return View(album);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var model = albumService.GetAll().Where(x => x.Id == id).Include(x => x.User)
                .Select(x => new EditAlbumViewModel()
                {
                    AlbumCover = x.CoverImage,
                    Title = x.Title,
                    UserId = x.UserId,
                    Id = x.Id
                }).FirstOrDefault();

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Update(EditAlbumViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (model.ImageFile != null)
            {
                var imageUploadResult = await cloudService.UploadImageAsync(model.ImageFile);

                Album album = albumService.GetAll().Where(x => x.Id == model.Id).FirstOrDefault();
                album.Title = model.Title;
                album.CoverImage = imageUploadResult;
                album.UserId = model.UserId;

                await albumService.UpdateAlbumAsync(album);
                return RedirectToAction("AllAlbums");
            }
            else
            {
                Album album = albumService.GetAll().Where(x => x.Id == model.Id).FirstOrDefault();
                album.Title = model.Title;
                album.CoverImage = model.AlbumCover;
                album.UserId = model.UserId;

                await albumService.UpdateAlbumAsync(album);
                return RedirectToAction("AllAlbums");
            }


        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id != null)
            {
                var tracks = await trackService.GetAllTracksAsync(x => x.AlbumId == id);
                tracks.ToList().ForEach(x => x.AlbumId = null);

                await likeService.DeleteAllLikesByAlbum(id);
                await albumService.DeleteAlbumByIdAsync(id);

                return RedirectToAction("AllAlbums");
            }
            return RedirectToAction("AllAlbums");

        }
        public async Task<IActionResult> AddAlbum()
        {
            var tempUser = await userManager.FindByEmailAsync(User.Identity.Name);
            User user = await userService.GetUserAsync(x => x.Email == tempUser.Email);

            var singles = await trackService.GetAllTracksAsync(x=>x.IsYoutube == false);

            if (User.IsInRole("Admin"))
            {
                singles = singles.Where(x => x.AlbumId is null).ToList();
            }
            else
            {
                singles = singles.Where(x => x.AlbumId is null && x.UserId == user.Id).ToList();
            }

            if (singles.Count() <= 0)
            {
                TempData["Message"] = "Не са намерени песни с аудио файлове.";
                return RedirectToAction("AllAlbums");
            }

            var model = new AddAlbumViewModel();
            Dictionary<int, string> pics = new Dictionary<int, string>();

           
            foreach (var item in singles)
            {
                pics.Add(item.Id, item.CoverImage);
            }
            var tracks = singles.Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Title,
                Selected = false
            }).ToList();
            model.Tracks = tracks;
            model.TrackPictures = pics;

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> AddAlbum(AddAlbumViewModel model)
        {
            if (ModelState.IsValid)
            {
                var tempUser = await userManager.FindByEmailAsync(User.Identity.Name);
                User user = await userService.GetUserAsync(x => x.Email == tempUser.Email);

                var imageUploadResult = await cloudService.UploadImageAsync(model.Picture);

                Album album = new Album
                {
                    Title = model.Title,
                    UserId = user.Id,
                    CoverImage = imageUploadResult
                };
                album.UserId = user.Id;
                await albumService.AddAlbumAsync(album);

                var tracks = await trackService.GetAllTracksAsync(x=>x.IsYoutube == false);

                if (model.SelectedTracksIds != null && model.SelectedTracksIds.Any())
                {
                    var selectedTracks = tracks.Where(x => model.SelectedTracksIds.Contains(x.Id)).ToList();

                    foreach (var track in selectedTracks)
                    {
                        track.AlbumId = album.Id;
                        await trackService.UpdateTrackAsync(track);
                    }

                }
                else 
                {
                    ModelState.AddModelError("SelectedTracksIds", "Моля изберете поне една песен.");
                }
                

                return RedirectToAction("AllAlbums");
            }
            else
            {
                var tempUser = await userManager.FindByEmailAsync(User.Identity.Name);
                User user = await userService.GetUserAsync(x => x.Email == tempUser.Email);

                var singles = await trackService.GetAllTracksAsync(x => x.IsYoutube == false);

                if (User.IsInRole("Admin"))
                {
                    singles = singles.Where(x => x.AlbumId is null).ToList();
                }
                else
                {
                    singles = singles.Where(x => x.AlbumId is null && x.UserId == user.Id).ToList();
                }

                if (singles.Count() <= 0)
                {
                    TempData["Message"] = "Не са намерени песни с аудио файлове.";
                    return RedirectToAction("AllAlbums");
                }
                Dictionary<int, string> pics = new Dictionary<int, string>();


                foreach (var item in singles)
                {
                    pics.Add(item.Id, item.CoverImage);
                }
                var tracks = singles.Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(),
                    Text = t.Title,
                    Selected = false
                }).ToList();
                model.Tracks = tracks;
                model.TrackPictures = pics;

                return View(model);
            }
        }

        public async Task<IActionResult> AllAlbums(AlbumFilterViewModel? filter)
        {
            var query = albumService.GetAll().AsQueryable();
            var filterModel = new AlbumFilterViewModel();

            if (string.IsNullOrEmpty(filter.Search))
            {
              
                var model = albumService.AllWithInclude().Include(x => x.User).Select(x => new AlbumViewModel()
                {
                    Id = x.Id,
                    Title = x.Title,
                    CoverImage = x.CoverImage,
                    UserName = x.User.Username
                }).ToList();

                if (!User.IsInRole("Admin"))
                {

HySound/Views/Home/Search.cshtml
@using HySound.ViewModels.Main
@model SearchViewModel


<div class="search-container">
    <div class="page-title">
        <h1>Търсене на съдържание</h1>
        <p class="subtitle">Открийте песни, албуми, изпълнители и плейлисти с един клик.</p>
    </div>

    <form asp-action="Search" asp-controller="Home" class="search-form">
        <div class="search-box">
            <input type="text" asp-for="SearchFilter" class="search-input" placeholder="Търси песни, албуми, изпълнители...">
            <button type="submit" class="search-btn">
                <i class="fas fa-search"></i> Търси
            </button>
        </div>

        <div class="search-filters">
            <input type="radio" id="filter-songs" asp-for="filter" value="songs" checked>
            <label for="filter-songs"><i class="fas fa-music"></i>&nbsp; Песни</label>

            <input type="radio" id="filter-users" asp-for="filter" value="users">
            <label for="filter-users"><i class="fas fa-user"></i>&nbsp; Изпълнители</label>

            <input type="radio" id="filter-albums" asp-for="filter" value="albums">
            <label for="filter-albums"><i class="fas fa-compact-disc"></i>&nbsp; Албуми</label>

            <input type="radio" id="filter-playlists" asp-for="filter" value="playlists">
            <label for="filter-playlists"><i class="fas fa-list"></i>&nbsp; Плейлисти</label>
        </div>
    </form>

    @if (Model != null)
    {
        <div class="search-results">
            @if (Model.User?.Any() == true)
            {
                <h2 class="section-title">Изпълнители</h2>
                <div class="artist-grid">
                    @foreach (var user in Model.User)
                    {
                        <div class="artist-card">
                            <a asp-controller="User" asp-action="UserDetails" asp-route-id="@user.Id">
                                <img src="@user.ProfilePicture" class="artist-img" alt="@user.Name">
                                <h3>@user.Name</h3>
                            </a>
                        </div>
                    }
                </div>
            }
            
            @if (Model.Tracks?.Any() == true)
            {
                <h2 class="section-title">Песни</h2>
                <div class="grid">
                    @foreach (var track in Model.Tracks)
                    {
                        <div class="result-card">
                            <a asp-controller="Track" asp-action="TrackDetails" asp-route-id="@track.TrackId">
                                <img src="@track.ImageLink" class="result-img" alt="@track.Title">
                                <div class="result-info">
                                    <h3>@track.Title</h3>
                                    <p>@track.UserName • @track.GenreName</p>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            }
            
            @if (Model.Albums?.Any() == true)
            {
                <h2 class="section-title">Албуми</h2>
                <div class="grid">
                    @foreach (var album in Model.Albums)
                    {
                        <div class="result-card">
                            <a asp-action="AlbumDetails" asp-controller="Album" asp-route-id="@album.Id">
                                <img src="@album.CoverImage" class="result-img" alt="@album.Title">
                                <div class="result-info">
                                    <h3>@album.Title</h3>
                                    <p>@album.UserName</p>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            }
            
            @if (Model.Playlists?.Any() == true)
            {
                <h2 class="section-title">Плейлисти</h2>
                <div class="grid">
                    @foreach (var playlist in Model.Playlists)
                    {
                        <div class="result-card">
                            <a asp-action="PlaylistDetails" asp-controller="Playlist" asp-route-id="@playlist.Id">
                                <img src="@playlist.CoverImage" class="result-img" alt="@playlist.Title">
                                <div class="result-info">
                                    <h3>@playlist.Title</h3>
                                    <p>@playlist.UserName</p>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            }

            @if (Model.User == null && Model.Tracks == null && Model.Albums == null && Model.Playlists == null && !string.IsNullOrEmpty(Model.SearchFilter))
            {
                <div class="no-results">
                    <h3>Не са намерени резултати</h3>
                    <p>Опитайте да търсите с различни ключови думи или изберете друга категория.</p>
                </div>
            }
        </div>
    }
</div>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

<style>
    /* Global Variables */
:root {
  --primary-color: #1DB954;
  --secondary-color: #191414;
  --text-color: #FFFFFF;
  --background-color: #121212;
  --card-background: #181818;
  --hover-color: #1ED760;
  --transition-speed: 0.3s;
}

/* 🔥 Search Container */
.search-container {
    max-width: 1200px;
    margin: 2rem auto 4rem;
    padding: 2.5rem;
    background: rgba(24, 24, 24, 0.9);
    border-radius: 20px;
    box-shadow: 0px 15px 40px rgba(0, 0, 0, 0.4);
    backdrop-filter: blur(20px);
}

/* 🔍 Page Title Section */
.page-title {
    text-align: center;
    margin-bottom: 2.5rem;
    position: relative;
}

.page-title h1 {
    font-size: 2.8rem;
    color: white;
    font-weight: 700;
    margin-bottom: 0.8rem;
    letter-spacing: -0.5px;
    text-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
}

.page-title .subtitle {
    font-size: 1.2rem;
    color: #b3b3b3;
    font-weight: normal;
    max-width: 600px;
    margin: 0 auto;
}

/* 🔍 Search Box */
.search-box {
    display: flex;
    align-items: center;
    background: #1a1a1a;
    border-radius: 50px;
    padding: 5px;
    width: 100%;
    border: 2px solid transparent;
    transition: all var(--transition-speed);
    margin-bottom: 1.5rem;
}

.search-box:focus-within {
    border-color: var(--primary-color);
    box-shadow: 0 0 0 4px rgba(29, 185, 84, 0.1);
}

.search-input {
    flex: 1;
    padding: 15px 20px;
    font-size: 1.1rem;
    border: none;
    border-radius: 50px;
    background: transparent;
    color: white;
    outline: none;
}

.search-input::placeholder {
    color: #808080;
}

.search-btn {
    background: var(--primary-color);
    border: none;
    padding: 12px 18px;
    margin-right: 5px;
    cursor: pointer;
    color: black;
    font-weight: bold;
    font-size: 1rem;
    border-radius: 50px;
    transition: all var(--transition-speed);
    display: flex;
    align-items: center;
    justify-content: center;
}

.search-btn:hover {
    background-color: var(--hover-color);
    transform: scale(1.05);
}

.search-btn i {
    font-size: 1.1rem;
}

/* 🎚️ Filters */
.search-filters {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    margin: 1.8rem 0;
    gap: 15px;
}

.search-filters input[type="radio"] {
    display: none;
}

.search-filters label {
    padding: 12px 24px;
    border-radius: 50px;
    background: #242424;
    color: #b3b3b3;
    font-weight: 600;
    cursor: pointer;
    transition: all var(--transition-speed);
    font-size: 0.95rem;
    min-width: 120px;
    text-align: center;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
    display: flex;
    align-items: center;
    justify-content: center;
}

.search-filters label:hover {
    background: #2a2a2a;
    transform: translateY(-2px);
}

.search-filters input[type="radio"]:checked + label {
    background: var(--primary-color);
    color: black;
    transform: scale(1.05);
    box-shadow: 0 6px 18px rgba(29, 185, 84, 0.3);
}

/* Section Titles */
.section-title {
    font-size: 1.6rem;
    margin: 2.5rem 0 1.2rem;
    font-weight: 700;
    position: relative;
    padding-left: 1rem;
    color: white;
}

.section-title::before {
    content: '';
    position: absolute;
    left: 0;
    top: 50%;
    transform: translateY(-50%);
    width: 4px;
    height: 24px;
    background-color: var(--primary-color);
    border-radius: 2px;
}

/* 🎵 Grid Layout */
.grid, .artist-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
    gap: 1.5rem;
    margin-top: 1.2rem;
}

.artist-grid {
    grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
}

/* 🎵 Result Cards */
.result-card {
    background: #181818;
    padding: 15px;
    border-radius: 12px;
    color: white;
    transition: all var(--transition-speed);
    cursor: pointer;
    box-shadow: 0px 8px 20px rgba(0, 0, 0, 0.2);
    overflow: hidden;
}

.result-card:hover {
    background: #242424;
    transform: translateY(-5px);
    box-shadow: 0px 12px 25px rgba(0, 0, 0, 0.4);
}

.result-card a {
    text-decoration: none;
    color: inherit;
    display: block;
}

/* 🖼️ Images */
.result-img {
    width: 100%;
    aspect-ratio: 1/1;
    object-fit: cover;
    border-radius: 8px;
    transition: transform var(--transition-speed);
}

.result-card:hover .result-img {
    transform: scale(1.05);
}

/* 🎵 Card Info */
.result-info {
    padding-top: 12px;
}

.result-info h3 {
    margin: 0 0 5px;
    font-size: 1rem;
    font-weight: 600;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.result-info p {
    font-size: 0.85rem;
    color: #b3b3b3;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

/* 🎤 Circular Artist Cards */
.artist-card {
    display: flex;
    flex-direction: column;
    align-items: center;
    background: #181818;
    padding: 20px 15px;
    border-radius: 15px;
    text-align: center;
    color: white;
    transition: all var(--transition-speed);
    cursor: pointer;
    box-shadow: 0px 8px 20px rgba(0, 0, 0, 0.2);
}

.artist-card:hover {
    background: #242424;
    transform: translateY(-5px);
    box-shadow: 0px 12px 25px rgba(0, 0, 0, 0.4);
}

.artist-card a {
    text-decoration: none;
    color: inherit;
    display: flex;
    flex-direction: column;
    align-items: center;
}

.artist-img {
    width: 100px;
    height: 100px;
    border-radius: 50%;
    object-fit: cover;
    margin-bottom: 12px;
    border: 3px solid rgba(255, 255, 255, 0.1);
    transition: border-color var(--transition-speed), transform var(--transition-speed);
}

.artist-card:hover .artist-img {
    border-color: var(--primary-color);
    transform: scale(1.05);
}

.artist-card h3 {
    font-size: 1rem;
    font-weight: 600;
    margin: 0;
}

/* 🎵 No Results Message */
.no-results {
    text-align: center;
    padding: 4rem 2rem;
    color: #b3b3b3;
}

.no-results h3 {
    font-size: 1.5rem;
    margin-bottom: 1rem;
}

.no-results p {
    font-size: 1.1rem;
    max-width: 500px;
    margin: 0 auto;
}

/* 🎵 Responsive Design */
@@media (max-width: 992px) {
    .search-container {
        max-width: 90%;
        padding: 2rem;
    }
    
    .page-title h1 {
        font-size: 2.4rem;
    }
}

@@media (max-width: 768px) {
    .search-filters {
        gap: 10px;
    }
    
    .search-filters label {
        padding: 10px 20px;
        min-width: 100px;
        font-size: 0.9rem;
    }
    
    .grid {
        grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    }
    
    .artist-grid {
        grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));
    }
    
    .page-title h1 {
        font-size: 2rem;
    }
    
    .page-title .subtitle {
        font-size: 1rem;
    }
}

@@media (max-width: 480px) {
    .search-container {
        padding: 1.5rem;
    }
    
    .grid {
        grid-template-columns: repeat(auto-fill, minmax(130px, 1fr));
        gap: 1rem;
    }
    
    .artist-grid {
        grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
    }
    
    .search-input {
        font-size: 1rem;
        padding: 12px 15px;
    }
    
    .artist-img {
        width: 80px;
        height: 80px;
    }
}
</style>